'''*************************************************
content     generate_report

version     0.0.2
date        24-03-2026

author      Harry Shaper <harryshaper@gmail.com>

*************************************************'''

import os
import getpass

from datetime import date, datetime


# *********************************************************************
# Create report
def generate_report(shoot_path, settings_data=None):
    """Creates a nicely readable report detailing all of the captures from the day."""

    settings_data = settings_data or {}

    project_details = settings_data.get("project_details", {})

    project_alias = project_details.get("project_name", "CODENAME") or "CODENAME"
    unit = project_details.get("unit", "MU") or "MU"

    shoot_date_raw = project_details.get("shoot_date", "")
    if shoot_date_raw:
        try:
            shoot_date = datetime.strptime(str(shoot_date_raw), "%Y-%m-%d").date()
        except ValueError:
            shoot_date = date.today()
    else:
        shoot_date = date.today()

    user = project_details.get("wrangler", "").strip() or getpass.getuser()

    # Get path variables
    shoot_day = os.path.basename(shoot_path)

    slate_list = [
        item for item in os.listdir(shoot_path)
        if os.path.isdir(os.path.join(shoot_path, item))
    ]
    setup_count = len(slate_list)

    report_file_name = shoot_day + "_report.yaml"
    report_path = os.path.join(shoot_path, report_file_name)

    # *********************************************************************#
    # Size checker
    def get_folder_size(folder_path):
        total_bytes = 0
        for root, dirs, files in os.walk(folder_path):
            for file in files:
                total_bytes += os.path.getsize(os.path.join(root, file))
        return total_bytes

    total_bytes = get_folder_size(shoot_path)
    total_mb = total_bytes / (1024 * 1024)
    total_gb = total_mb / 1024

    # *********************************************************************#
    # Date/Time & User details
    timestamp = datetime.now().strftime("%Y-%m-%d @ %H:%M")

    # *********************************************************************#
    # Create yaml and fill in details
    with open(report_path, "w", encoding="utf-8") as f:
        # Header
        f.write(f"{project_alias}:\n")
        f.write(f"{unit} - {shoot_day}:\n")
        f.write(f"DATE - {shoot_date}:\n")
        f.write(f"  setup_count: {setup_count}\n")
        f.write(f"  #------------------------------------------------#\n\n")

        # Loop over all slates
        for slate in slate_list:
            slate_path = os.path.join(shoot_path, slate)
            f.write(f"  Slate: {slate}:\n")

            for datatype in os.listdir(slate_path):
                datatype_path = os.path.join(slate_path, datatype)

                if os.path.isdir(datatype_path):
                    datatype_count = len([
                        item for item in os.listdir(datatype_path)
                        if os.path.isdir(os.path.join(datatype_path, item))
                    ])
                    f.write(f"    {datatype}: {datatype_count}\n")

            f.write("\n")

        f.write(f"  Total captured size: {total_gb:.2f} GB ({total_mb:.1f} MB)\n")
        f.write(f"  Report generated by: {user}\n")
        f.write(f"  Report generated: {timestamp}\n")