project_details:
  project_name: Badlands
  shoot_date: '2026-03-25'
  wrangler: Mac
  unit: 2nd Unit
package_settings:
  rename_package: true
  remove: _dump
  prefix: ''
  suffix: _SORTED
  subfolder_images: true
  generate_yaml: true
  notify_by_email: true
  flag_empty_folders: false
