project_details:
  project_name: SKYRIM
package_settings:
  rename_package: true
  remove: _TEST
  prefix: ''
  suffix: _OUTPUT
  generate_yaml: true
  notify_by_email: true
  flag_empty_folders: false
rename_rules:
- name: TEXTURES
  data_type: TEXTURES
  sort_by: ASSET
  split_image_type: true
  delete_empty_folders: false
  naming_rule: '{ALL}_{DATE}_{DATA_TYPE}_{FOCAL}'
- name: HDRI
  data_type: HDRI
  sort_by: SLATE
  split_image_type: false
  delete_empty_folders: false
  naming_rule: '{ALL}_{DATA_TYPE}_{DATE}'
