project_details:
  project_name: Skyrim
package_settings:
  rename_package: true
  remove: _dump
  prefix: ''
  suffix: _SORTED
  generate_yaml: false
  notify_by_email: false
  create_revert_manifest: true
rename_rules:
- name: HDRI
  data_type: HDRI
  sort_by: SLATE
  split_image_type: true
  delete_empty_folders: false
  naming_rule: '{DATE}_{DATA_TYPE}_{ALL}'
- name: PANO
  data_type: PANO
  sort_by: KEEP STRUCTURE
  split_image_type: false
  delete_empty_folders: false
  naming_rule: '{DATE}_{REST}_{DATA_TYPE}_{FIRST}'
- name: OVERVIEW
  data_type: OVERVIEW
  sort_by: SLATE
  split_image_type: false
  delete_empty_folders: false
  naming_rule: '{DATE}_{DATA_TYPE}_{ALL}'
