show_profile:
  name: "badlands_2U"
  auto_load_defaults: true   # Set to false if you want a blank UI each time
  apply_project_name_on_startup: true
  apply_wranglers_on_startup: true
  apply_email_defaults_on_startup: true

project_defaults:
  project_name: "Badlands"
  unit: "2nd Unit"

wrangler_defaults:
  options:
    - ""
    - "Mac"
    - "Charlie"
    - "Dennis"
    - "Dee"

  default_selection: "Mac"

email_defaults:
  enabled_by_default: false
  subject: "{project_name} {clean_package_name} ready for ingestion"
  body: |
    Hi,

    {clean_package_name} is packaged and ready for ingestion.

    Thanks,
    -Mac
    
  to:
    - "data.team@studio.com"
    - "production@studio.com"
  cc:
    - "vfxsupervisor@studio.com"

browser_defaults:
  preferred_browser: "chrome"   # Options: "default", "chrome", "edge"